// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ZGSlSC9Ur66e0p8UE6D-RfNOtA7rLmE',
    appId: '1:690960064012:web:cd2835d3a66122b6639829',
    messagingSenderId: '690960064012',
    projectId: 'chat-app-5743a',
    authDomain: 'chat-app-5743a.firebaseapp.com',
    storageBucket: 'chat-app-5743a.firebasestorage.app',
    measurementId: 'G-1Q3WLMKCLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKuYNSbhOJLwc0i1Lg98GZv_Q-RLIDI84',
    appId: '1:690960064012:android:c32e13f0448bb796639829',
    messagingSenderId: '690960064012',
    projectId: 'chat-app-5743a',
    storageBucket: 'chat-app-5743a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAySspLk9SgwHbjrmdAt5FQpC0ULjGp3J8',
    appId: '1:690960064012:ios:a82e98d835884ff3639829',
    messagingSenderId: '690960064012',
    projectId: 'chat-app-5743a',
    storageBucket: 'chat-app-5743a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAySspLk9SgwHbjrmdAt5FQpC0ULjGp3J8',
    appId: '1:690960064012:ios:a82e98d835884ff3639829',
    messagingSenderId: '690960064012',
    projectId: 'chat-app-5743a',
    storageBucket: 'chat-app-5743a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ZGSlSC9Ur66e0p8UE6D-RfNOtA7rLmE',
    appId: '1:690960064012:web:cc239c4a0c9973af639829',
    messagingSenderId: '690960064012',
    projectId: 'chat-app-5743a',
    authDomain: 'chat-app-5743a.firebaseapp.com',
    storageBucket: 'chat-app-5743a.firebasestorage.app',
    measurementId: 'G-E0TX3B3E27',
  );
}
